// Type Of Action
export const TOOGLE_PROJECT_FORM_MODAL = 'TOOGLE_PROJECT_FORM_MODAL';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_PROJECT_FULFILLED = 'FETCH_PROJECT_FULFILLED';
export const ADD_PROJECT = 'ADD_PROJECT';
