// Type Of Action
export const TOOGLE_PROJECT_FORM_MODAL = 'TOOGLE_PROJECT_FORM_MODAL';
export const TOOGLE_LOADING = 'TOOGLE_LOADING';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_PROJECT_FULFILLED = 'FETCH_PROJECT_FULFILLED';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
